### ISSUE TITLE
Distribute via Homebrew fonts

### ISSUE THREAD

**Issue by xrisk** [evilmartians/mono#1]

**Comment by alexmyczko** [comment]
and debian, and google fonts, and fnt (https://github.com/alexmyczko/fnt)

**Comment by caraya** [comment]
Why would you distribute fonts via Homebrew? Do you know if it's even possible?

**Comment by alexmyczko** [comment]
Possible yes: https://github.com/Homebrew/homebrew-cask-fonts/tree/master/Casks

I would’t, that is why I wrote `fnt`

**Comment by caraya** [comment]
Casks are applications that come from either a .DMG or a .PKG installer, unless you want to go through the process of creating a notarized app for just a single font, that's up to you. Interestingly enough, I only found three font-related cask packages when searching the brew cask archive, and none of them are individual fonts, that's why I asked if it was possible.

Creating casks and formulae for Homebrew is tedious but possible, but whether it's possible to create a package or formula from a single font file that's another question altogether.

From what I understand you have to package the fonts you submit for approval at Debian.

I don't know about Google fonts and I'm not going to argue with the author of fnt about whether it makes sense to do so or not

**Comment by xrisk** [comment]
> asks are applications that come from either a .DMG or a .PKG installer

Incorrect. See https://github.com/Homebrew/homebrew-cask-fonts/blob/master/CONTRIBUTING.md#adding-a-font-cask

**Comment by caraya** [comment]
Thank you for pointing this out. I wasn't aware that it existed since it's an add-in cask that you need to tap to use

The cask repository you mentioned (which is not the main cask repository even though it's in the same organization) requires you to add the font to Google Fonts and have the font automatically appear in the cask repo. They will make exceptions to the Google Fonts requirements for popular fonts, but the manual addition to the repo is not guaranteed. 

so, it's still not a matter of just writing a formula or a cask and expecting it to be included just because the formula was submitted.  The process of submitting a font to Google Fonts is tedious and has a lot of requirements  (https://github.com/google/fonts/blob/main/CONTRIBUTING.md)

I'm not a maintainer of this font, I was curious as to whether it was possible or not. It is possible but not in a way that doesn't require extra work from the maintainers and users. Whether they want to undertake it is up to them

**Comment by gaetschwartz** [comment]
This is available in `homebrew/cask-fonts/font-martian-mono`. You can install it by using 
```bash
brew tap homebrew/cask-fonts
brew install homebrew/cask-fonts/font-martian-mono
```

**Comment by romashamin** [comment]
Yep, here it is: https://github.com/Homebrew/homebrew-cask-fonts/commit/7873c59823fa1bce7126ac71cee6d51fafa6d5ad /cc @y-nk and @miccal

Closing this.
